"use client";
import React from "react"; // Corrected import for React
import "./globals.css";
import Header from "@/components/Header";
import { Sidebar } from "@/components/SiderBar";
import { usePathname } from "next/navigation";

// Removed metadata export
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className="flex h-screen w-screen overflow-x-hidden bg-[#f8f7f4]">
        {!["/login", "/Receptionist"].includes(pathname) && <Sidebar />}
        <div className={`flex-1 flex flex-col ${pathname !== "/Receptionist" ? "ml-64" : ""}`}>
          <Header />
          <main className="flex-1 p-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
