import { Inter } from "next/font/google";
import type React from "react"; // Added import for React
import "./globals.css";
import { Metadata } from "next/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen bg-[#f8f7f4]">{children}</div>
      </body>
    </html>
  );
}
